install_driver: True

# Config for tcp tunning in sysctl

sysctl_config:
  net.core.rmem_max: 2147483647
  net.core.wmem_max: 2147483647
  net.ipv4.tcp_rmem: 4096 87380 2147483647
  net.ipv4.tcp_wmem: 4096 65536 2147483647
  net.core.default_qdisc: fq_codel
  net.ipv4.tcp_mtu_probing: 1
  net.core.netdev_max_backlog: 50000
  net.ipv4.tcp_max_syn_backlog: 30000
  net.ipv4.tcp_tw_reuse: 1
  net.ipv4.tcp_slow_start_after_idle: 0
  net.nf_conntrack_max: 2000000
